language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - hhvm

script:
  - time php -n -d memory_limit=512M array_memory.php
  - time php -n -d memory_limit=512M binarytrees.php 15

notifications:
 email: false
